import json
import shutil
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest.mock import patch

from mo2_agent_toolkit import cli
from mo2_agent_toolkit.workflow import (
    WorkflowError,
    _copy_selected,
    _list_7z,
    _place_mods,
    apply_plan,
    collect_batch,
    create_plan,
    fomod_options,
    fomod_preview,
    prepare_batch,
    archive_source,
)

SEPARATOR = "—————— 其他模组生成 ——————_separator"
HEADER = "# This file was automatically generated by Mod Organizer."


class WorkflowTests(unittest.TestCase):
    def instance(self, root: Path) -> Path:
        instance = root / "MO2"
        for name in cli.REQUIRED_DIRS:
            (instance / name).mkdir(parents=True, exist_ok=True)
        profile = instance / "profiles" / "Default"
        profile.mkdir(parents=True)
        (profile / "modlist.txt").write_text(
            f"{HEADER}\n+{SEPARATOR}\n+Ordinary Existing\n*DLC: Dawnguard\n",
            encoding="utf-8-sig",
        )
        (profile / "plugins.txt").write_text(f"{HEADER}\n", encoding="utf-8-sig")
        (profile / "loadorder.txt").write_text(f"{HEADER}\n", encoding="utf-8-sig")
        return instance

    def archive(self, path: Path, fomod: bool = False) -> None:
        with zipfile.ZipFile(path, "w") as archive:
            archive.writestr("Wrapper/Test.esp", "x")
            archive.writestr("Wrapper/SKSE/Plugins/test.dll", "x")
            if fomod:
                archive.writestr(
                    "Wrapper/fomod/ModuleConfig.xml",
                    '<config><requiredInstallFiles><file source="Test.esp" destination="Test.esp"/></requiredInstallFiles>'
                    '<installSteps><installStep name="Options"><optionalFileGroups><group name="Patch" type="SelectAny">'
                    '<plugins><plugin name="Optional"><files><folder source="SKSE" destination="SKSE"/></files>'
                    '<typeDescriptor><type name="Optional"/></typeDescriptor></plugin></plugins></group>'
                    '</optionalFileGroups></installStep></installSteps></config>',
                )

    def placement(self) -> dict:
        return {"after_mod": SEPARATOR}

    def test_7z_listing_excludes_archive_header_record(self):
        listing = """Path = C:\\Downloads\\Example.rar
Type = Rar

----------
Path = Data\\Example.esp
Size = 1
Packed Size = 1
Attributes = A
"""
        completed = type("Result", (), {"returncode": 0, "stdout": listing, "stderr": ""})()
        with patch("mo2_agent_toolkit.workflow.subprocess.run", return_value=completed):
            entries = _list_7z(Path(r"C:\Downloads\Example.rar"), "7z.exe")
        self.assertEqual([item["Path"] for item in entries], [r"Data\Example.esp"])

    def test_plan_reports_layout_context_and_requires_placement(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Elegant.zip"; self.archive(archive)
            provider = instance / "mods" / "Ordinary Existing"; provider.mkdir(); (provider / "Test.esp").write_text("old", encoding="utf-8")
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            self.assertEqual(plan["layout"]["nesting_root"], "Wrapper")
            self.assertTrue(plan["layout"]["flatten"])
            self.assertTrue(plan["placement"]["required"])
            self.assertIn(SEPARATOR, [item["name"] for item in plan["modlist_context"]["separators"]])
            self.assertEqual(plan["modlist_context"]["conflict_file_providers"][0]["mod"], "Ordinary Existing")
            naming=plan["modlist_context"]["naming_conventions"]
            self.assertTrue(naming["explicit_name_required"]); self.assertGreaterEqual(naming["categorized_mods"]+naming["uncategorized_mods"],1)
            self.assertIn("placement_decision_order",plan["modlist_context"])

    def test_plan_surfaces_profile_naming_conventions_and_related_mods(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'; archive=root/'Babo Dialogue.zip'; self.archive(archive)
            lines=(profile/'modlist.txt').read_text(encoding='utf-8-sig').replace('+Ordinary Existing','+[NSFW] 对话扩展——Babo Dialogue Base\n+[NSFW] 动画框架——Other Framework\n+Ordinary Existing')
            (profile/'modlist.txt').write_text(lines,encoding='utf-8-sig',newline='\n')
            plan=create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},root/'plans',name='[NSFW] 对话扩展——Babo Dialogue Patch')
            context=plan['modlist_context']; self.assertEqual(context['naming_conventions']['requested_name'],'[NSFW] 对话扩展——Babo Dialogue Patch')
            self.assertEqual(context['naming_conventions']['category_prefixes'][0]['prefix'],'[NSFW]')
            related=context['related_mods']; self.assertEqual(related[0]['name'],'[NSFW] 对话扩展——Babo Dialogue Base')
            self.assertIn('babo',related[0]['matching_tokens']); self.assertIn('dialogue',related[0]['matching_tokens'])

    def test_duplicate_anchor_is_rejected_before_any_deduplication(self):
        lines = [HEADER, "+Anchor", "-Anchor", "+Other"]
        with self.assertRaises(WorkflowError) as caught:
            _place_mods(lines, ["New"], {"after_mod": "Anchor"})
        self.assertIn("duplicated", str(caught.exception))

    def test_apply_flattens_then_rescans_plugins_and_places_after_separator(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]):
                result = apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            target = instance / "mods" / plan["mod_name"]
            self.assertTrue((target / "Test.esp").exists())
            self.assertFalse((target / "Wrapper").exists())
            self.assertEqual(result["plugins_enabled"], ["Test.esp"])
            lines = (instance / "profiles" / "Default" / "modlist.txt").read_text(encoding="utf-8-sig").splitlines()
            self.assertEqual(lines.index("+" + plan["mod_name"]), lines.index("+" + SEPARATOR) + 1)
            self.assertEqual(result["final_placement"]["file_direction"]["previous_mod"], SEPARATOR)

    def test_invalid_staged_root_is_rejected_before_commit(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Invalid.zip"
            with zipfile.ZipFile(archive, "w") as zipped:
                zipped.writestr("Wrapper/docs/manual.bin", "x")
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            original = (instance / "profiles" / "Default" / "modlist.txt").read_bytes()
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]):
                with self.assertRaises(WorkflowError) as caught:
                    apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            self.assertIn("current_root_entries", caught.exception.details)
            self.assertIn("Wrapper", caught.exception.details["suspected_wrapper_directories"])
            self.assertFalse((instance / "mods" / plan["mod_name"]).exists())
            self.assertEqual((instance / "profiles" / "Default" / "modlist.txt").read_bytes(), original)

    def test_missing_anchor_stops_without_highest_priority_fallback(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]):
                with self.assertRaises(WorkflowError) as caught:
                    apply_plan(root / "plans" / f"{plan['id']}.json", None, {"after_mod": "Missing"})
            self.assertIn("missing", str(caught.exception))
            self.assertFalse((instance / "_agent_toolkit_backups" / plan["id"]).exists())

    def test_failure_restores_old_mod_and_all_profile_files(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            old = instance / "mods" / "Example"; old.mkdir(); (old / "old.txt").write_text("old", encoding="utf-8")
            profile = instance / "profiles" / "Default"
            modlist = (profile / "modlist.txt").read_text(encoding="utf-8-sig").replace("+Ordinary Existing", "+Example\n+Ordinary Existing")
            (profile / "modlist.txt").write_text(modlist, encoding="utf-8-sig", newline="\n")
            originals = {name: (profile / name).read_bytes() for name in ("modlist.txt", "plugins.txt", "loadorder.txt")}
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            failed = {"status": "failed", "issues": [{"severity": "error", "what": "forced"}]}
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]), patch("mo2_agent_toolkit.workflow.audit_profile", return_value=failed):
                with self.assertRaises(WorkflowError):
                    apply_plan(root / "plans" / f"{plan['id']}.json", None)
            self.assertEqual((old / "old.txt").read_text(encoding="utf-8"), "old")
            for name, content in originals.items():
                self.assertEqual((profile / name).read_bytes(), content)

    def test_multiple_mods_keep_high_to_low_order_and_untouched_order(self):
        lines = [HEADER, "+High", "+" + SEPARATOR, "+Ordinary A", "+Ordinary B"]
        updated, _ = _place_mods(lines, ["New High", "New Low"], {"after_mod": SEPARATOR})
        self.assertEqual(updated, [HEADER, "+High", "+" + SEPARATOR, "+New High", "+New Low", "+Ordinary A", "+Ordinary B"])

    def test_apply_blocks_while_mo2_runs(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "A.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=["ModOrganizer.exe"]):
                with self.assertRaises(WorkflowError) as caught:
                    apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            self.assertEqual(caught.exception.code, 3)

    def test_fomod_requires_explicit_selections(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Fomod.zip"; self.archive(archive, True)
            with self.assertRaises(WorkflowError) as caught:
                create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            self.assertEqual(caught.exception.code, 1)
            self.assertEqual(caught.exception.details["layout"]["nesting_root"], "Wrapper")
            self.assertEqual(caught.exception.details["recommended_selections"], {"0:0": []})
            self.assertEqual(caught.exception.details["recommended_resolution"]["visible_pages"][0]["name"], "Options")

    def test_archive_failure_is_post_commit_warning(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default", "archive_after_install": True, "archive_directory": str(root / "archive")}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]), patch("mo2_agent_toolkit.workflow.archive_source", side_effect=OSError("denied")):
                result = apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            self.assertEqual(result["status"], "installed_with_warnings")
            self.assertTrue((instance / "mods" / plan["mod_name"]).is_dir())

    def test_update_preserves_position_enable_state_and_disables_new_plugin(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/"profiles"/"Default"
            target=instance/"mods"/"Example"; target.mkdir(); (target/"Old.esp").write_text("old",encoding="utf-8"); (target/"Removed.esp").write_text("old",encoding="utf-8")
            (target/"meta.ini").write_text("[General]\ncategory=42\nversion=1.0\n",encoding="utf-8")
            modlist=(profile/"modlist.txt").read_text(encoding="utf-8-sig").replace("+Ordinary Existing","-Example\n+Ordinary Existing")
            (profile/"modlist.txt").write_text(modlist,encoding="utf-8-sig",newline="\n")
            (profile/"plugins.txt").write_text(f"{HEADER}\n*Old.esp\n*Removed.esp\n",encoding="utf-8-sig")
            (profile/"loadorder.txt").write_text(f"{HEADER}\nOld.esp\nRemoved.esp\n",encoding="utf-8-sig")
            archive=root/"Example.zip"
            with zipfile.ZipFile(archive,"w") as z:
                z.writestr("Old.esp","new"); z.writestr("New.esp","new")
            source={"provider":"nexus","mod_id":133568,"file_id":751019,"official_filename":"Example Official.zip","version":"1.0.9","last_modified":"2026-05-11T10:06:29Z"}
            plan=create_plan(archive,{"mo2_instance_path":str(instance),"profile":"Default"},root/"plans",source_metadata=source)
            self.assertEqual(plan["operation"],"update"); self.assertFalse(plan["placement"]["required"])
            with patch("mo2_agent_toolkit.workflow.mo2_running",return_value=[]):
                result=apply_plan(root/"plans"/f"{plan['id']}.json",None)
            self.assertIn("-Example",(profile/"modlist.txt").read_text(encoding="utf-8-sig").splitlines())
            plugin_lines=(profile/"plugins.txt").read_text(encoding="utf-8-sig").splitlines()
            self.assertIn("*Old.esp",plugin_lines); self.assertNotIn("New.esp",plugin_lines); self.assertNotIn("*New.esp",plugin_lines); self.assertNotIn("*Removed.esp",plugin_lines)
            self.assertNotIn("Removed.esp",(profile/"loadorder.txt").read_text(encoding="utf-8-sig").splitlines())
            self.assertEqual(result["plugin_changes"]["new_plugins_unregistered"],["New.esp"]); self.assertEqual(result["plugin_changes"]["removed_plugins"],["Removed.esp"])
            self.assertEqual(result["content_audit"]["status"],"passed")
            meta=(target/"meta.ini").read_text(encoding="utf-8-sig")
            self.assertIn("category=42",meta); self.assertIn(r"1\fileid=751019",meta); self.assertNotIn("\f",meta)

    def test_update_rejects_state_drift_before_transaction(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/"profiles"/"Default"
            target=instance/"mods"/"Example"; target.mkdir(); (target/"Test.esp").write_text("old",encoding="utf-8")
            modlist=(profile/"modlist.txt").read_text(encoding="utf-8-sig").replace("+Ordinary Existing","+Example\n+Ordinary Existing")
            (profile/"modlist.txt").write_text(modlist,encoding="utf-8-sig",newline="\n")
            archive=root/"Example.zip"; self.archive(archive)
            plan=create_plan(archive,{"mo2_instance_path":str(instance),"profile":"Default"},root/"plans")
            changed=(profile/"modlist.txt").read_text(encoding="utf-8-sig").replace("+Example","-Example")
            (profile/"modlist.txt").write_text(changed,encoding="utf-8-sig",newline="\n")
            with patch("mo2_agent_toolkit.workflow.mo2_running",return_value=[]),self.assertRaises(WorkflowError):
                apply_plan(root/"plans"/f"{plan['id']}.json",None)
            self.assertFalse((instance/"_agent_toolkit_backups"/plan["id"]).exists())

    def test_archive_source_same_path_is_safe_noop(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); source=root/"Example.zip"; source.write_bytes(b"archive")
            result=archive_source(source,root)
            self.assertEqual(result["status"],"already_in_archive"); self.assertTrue(source.exists())


    def test_batch_collect_by_file_id(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); (root / "CoolMod-12345.zip").write_bytes(b"x")
            data = prepare_batch(10, [12345], root, root / "sessions", False)
            result = collect_batch(root / "sessions" / f"{data['id']}.json")
            self.assertEqual(result["status"], "collected")



    def test_plan_rejects_malformed_nexus_source_metadata(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); archive=root/"Example.zip"; self.archive(archive)
            cfg={"mo2_instance_path":str(instance),"profile":"Default"}
            bad={"provider":"nexus","mod_id":133568,"file_id":751019,"official_filename":"../bad.zip","version":"1.0.9"}
            with self.assertRaises(WorkflowError) as caught:
                create_plan(archive,cfg,root/"plans",source_metadata=bad)
            self.assertIn("safe Windows basename",str(caught.exception))

    def test_content_audit_failure_rolls_back_mod_and_profile(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/"profiles"/"Default"
            target=instance/"mods"/"Example"; target.mkdir(); (target/"Old.esp").write_text("old",encoding="utf-8")
            original={name:(profile/name).read_bytes() for name in ("modlist.txt","plugins.txt","loadorder.txt")}
            modlist=(profile/"modlist.txt").read_text(encoding="utf-8-sig").replace("+Ordinary Existing","+Example\n+Ordinary Existing")
            (profile/"modlist.txt").write_text(modlist,encoding="utf-8-sig",newline="\n")
            original={name:(profile/name).read_bytes() for name in ("modlist.txt","plugins.txt","loadorder.txt")}
            archive=root/"Example.zip"; self.archive(archive)
            plan=create_plan(archive,{"mo2_instance_path":str(instance),"profile":"Default"},root/"plans")
            failed={"status":"failed","expected_files":2,"installed_files":1,"missing":["Test.esp"],"extra":[],"different":[]}
            with patch("mo2_agent_toolkit.workflow.mo2_running",return_value=[]), patch("mo2_agent_toolkit.workflow._compare_manifests",return_value=failed), self.assertRaises(WorkflowError):
                apply_plan(root/"plans"/f"{plan['id']}.json",None)
            self.assertEqual((target/"Old.esp").read_text(encoding="utf-8"),"old")
            for name,content in original.items():self.assertEqual((profile/name).read_bytes(),content)
            rolled=json.loads((root/"plans"/f"{plan['id']}.json").read_text(encoding="utf-8"))
            self.assertEqual(rolled["status"],"rolled_back")

    def test_archive_source_uses_unique_collision_suffix(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); source_dir=root/"source"; destination=root/"archive"
            source_dir.mkdir(); destination.mkdir(); source=source_dir/"Example.zip"; source.write_bytes(b"new")
            (destination/"Example.zip").write_bytes(b"old"); (destination/"Example-42.zip").write_bytes(b"older")
            result=archive_source(source,destination,"42")
            self.assertEqual(Path(result["path"]).name,"Example-42-2.zip")
            self.assertEqual(Path(result["path"]).read_bytes(),b"new")



    def test_fomod_without_option_groups_plans_required_files(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); archive=root/'RequiredOnly.zip'
            with zipfile.ZipFile(archive,'w') as z:
                z.writestr('fomod/ModuleConfig.xml','<config><moduleName>Required Only</moduleName><requiredInstallFiles><file source="Required.esp" destination="Required.esp"/></requiredInstallFiles></config>')
                z.writestr('Required.esp','plugin')
            plan=create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},root/'plans')
            self.assertEqual(plan['fomod_resolution']['visible_pages'],[])
            self.assertEqual(plan['fomod_resolution']['plugins'],['Required.esp'])
            self.assertEqual(plan['selected_files'][0]['destination'],'Required.esp')

    def test_pyfomod_evaluates_visibility_types_conditionals_and_folder_plugins(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'
            provider=instance/'mods'/'Ordinary Existing'; provider.mkdir(); (provider/'Dependency.esp').write_text('dep',encoding='utf-8')
            (profile/'plugins.txt').write_text(f'{HEADER}\n*Dependency.esp\n',encoding='utf-8-sig')
            (profile/'loadorder.txt').write_text(f'{HEADER}\nDependency.esp\n',encoding='utf-8-sig')
            archive=root/'Conditional.zip'
            xml='''<config><moduleName>Conditional</moduleName><installSteps order="Explicit">
              <installStep name="Hidden"><visible><fileDependency file="Absent.esp" state="Active"/></visible><optionalFileGroups><group name="Hidden" type="SelectAny"><plugins><plugin name="Never"><typeDescriptor><type name="Optional"/></typeDescriptor></plugin></plugins></group></optionalFileGroups></installStep>
              <installStep name="Choice"><optionalFileGroups order="Explicit"><group name="Core" type="SelectExactlyOne"><plugins order="Explicit">
                <plugin name="Core Files"><files><folder source="Core" destination=""/></files><conditionFlags><flag name="choice">yes</flag></conditionFlags>
                  <typeDescriptor><dependencyType><defaultType name="NotUsable"/><patterns><pattern><dependencies operator="And"><fileDependency file="Dependency.esp" state="Active"/></dependencies><type name="Recommended"/></pattern></patterns></dependencyType></typeDescriptor>
                </plugin></plugins></group></optionalFileGroups></installStep>
              <installStep name="Visible Patch"><visible><flagDependency flag="choice" value="yes"/></visible><optionalFileGroups order="Explicit"><group name="Patch" type="SelectExactlyOne"><plugins order="Explicit">
                <plugin name="Patch"><files><file source="Patch/visible.txt" destination="visible.txt"/></files><typeDescriptor><type name="Optional"/></typeDescriptor></plugin>
              </plugins></group></optionalFileGroups></installStep></installSteps>
              <conditionalFileInstalls><patterns><pattern><dependencies operator="And"><flagDependency flag="choice" value="yes"/></dependencies><files><file source="Conditional/result.txt" destination="result.txt" priority="1"/><file source="Conditional/result.txt" destination="result-copy.txt" priority="2"/></files></pattern></patterns></conditionalFileInstalls>
            </config>'''
            with zipfile.ZipFile(archive,'w') as z:
                z.writestr('fomod/ModuleConfig.xml',xml); z.writestr('Core/Projected.esp','plugin')
                z.writestr('Patch/visible.txt','visible'); z.writestr('Conditional/result.txt','conditional')
            game=root/'Game'; (game/'Data').mkdir(parents=True)
            config={'mo2_instance_path':str(instance),'profile':'Default','skyrim_game_path':str(game)}
            preview=fomod_preview(archive,config)
            self.assertEqual([page['name'] for page in preview['visible_pages']],['Choice','Visible Patch'])
            self.assertEqual(preview['visible_pages'][0]['groups'][0]['options'][0]['type'],'Recommended')
            self.assertEqual(preview['recommended_selections'],{'1:0':['1:0:0'],'2:0':['2:0:0']})
            selections={'1:0':['1:0:0'],'2:0':['2:0:0']}
            plan=create_plan(archive,config,root/'plans',selections=selections)
            resolution=plan['fomod_resolution']
            self.assertEqual(plan['fomod']['engine'],'pyfomod-1.2.1')
            self.assertEqual([p['name'] for p in resolution['visible_pages']],['Choice','Visible Patch'])
            self.assertEqual(resolution['visible_pages'][0]['groups'][0]['options'][0]['type'],'Recommended')
            self.assertEqual(resolution['flags'],{'choice':'yes'})
            self.assertEqual(resolution['plugins'],['Projected.esp'])
            destinations={item['destination'].replace('\\','/') for item in plan['selected_files']}
            self.assertEqual(destinations,{'Projected.esp','visible.txt','result.txt','result-copy.txt'})
            priorities={item['destination'].replace('\\','/'):item['priority'] for item in plan['selected_files']}
            self.assertEqual((priorities['result.txt'],priorities['result-copy.txt']),(1,2))
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]):
                result=apply_plan(root/'plans'/f"{plan['id']}.json",None,self.placement())
            target=instance/'mods'/plan['mod_name']
            self.assertTrue((target/'Projected.esp').is_file()); self.assertTrue((target/'visible.txt').is_file()); self.assertTrue((target/'result.txt').is_file()); self.assertTrue((target/'result-copy.txt').is_file())
            self.assertEqual(result['plugins_enabled'],['Projected.esp'])


    def test_fomod_copy_rejects_source_and_destination_path_escape(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); source=root/'source'; destination=root/'destination'; source.mkdir(); destination.mkdir()
            (source/'safe.txt').write_text('safe',encoding='utf-8')
            cases=[
                ({'source':'../secret.txt','destination':'safe.txt','priority':0},'source'),
                ({'source':'safe.txt','destination':'../escaped.txt','priority':0},'destination'),
                ({'source':'C:/Windows/win.ini','destination':'safe.txt','priority':0},'source'),
                ({'source':'safe.txt','destination':'C:/escaped.txt','priority':0},'destination'),
                ({'source':'safe.txt','destination':'//server/share/escaped.txt','priority':0},'destination'),
            ]
            for item,label in cases:
                with self.subTest(label=label,item=item), self.assertRaises(WorkflowError) as caught:
                    _copy_selected(source,destination,[item])
                self.assertEqual(caught.exception.code,3)
            self.assertEqual(list(destination.iterdir()),[])

    def test_pyfomod_critical_parser_warning_is_a_safe_stop(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); archive=root/'InvalidEnum.zip'
            xml="""<config><installSteps><installStep name="Choice"><optionalFileGroups><group name="Core" type="SelectExactlyOn"><plugins><plugin name="Core"><files><file source="Core.esp" destination="Core.esp"/></files><typeDescriptor><type name="Optional"/></typeDescriptor></plugin></plugins></group></optionalFileGroups></installStep></installSteps></config>"""
            with zipfile.ZipFile(archive,'w') as z:z.writestr('fomod/ModuleConfig.xml',xml); z.writestr('Core.esp','plugin')
            with self.assertRaises(WorkflowError) as caught:fomod_preview(archive,{'mo2_instance_path':str(instance),'profile':'Default'})
            self.assertEqual(caught.exception.code,1)
            warnings=caught.exception.details['validation_warnings']
            self.assertTrue(any(item['type']=='InvalidEnumWarning' and item['critical'] for item in warnings))

    def test_fomod_missing_dependency_requires_valid_game_data(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); archive=root/'GameDependency.zip'
            xml="""<config><moduleDependencies><fileDependency file="Skyrim.esm" state="Active"/></moduleDependencies><requiredInstallFiles><file source="Core.esp" destination="Core.esp"/></requiredInstallFiles></config>"""
            with zipfile.ZipFile(archive,'w') as z:z.writestr('fomod/ModuleConfig.xml',xml); z.writestr('Core.esp','plugin')
            with self.assertRaises(WorkflowError) as caught:create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},root/'plans')
            self.assertEqual(caught.exception.code,1)
            self.assertIn('valid Skyrim Data',str(caught.exception))
            self.assertEqual(caught.exception.details['dependencies'],['Skyrim.esm'])

    def test_fomod_dependency_can_be_resolved_from_overwrite_without_game_root(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'; archive=root/'OverwriteDependency.zip'
            overwrite=instance/'overwrite'; overwrite.mkdir(exist_ok=True); (overwrite/'Generated.esp').write_text('generated',encoding='utf-8')
            (profile/'plugins.txt').write_text(f'{HEADER}\n*Generated.esp\n',encoding='utf-8-sig')
            (profile/'loadorder.txt').write_text(f'{HEADER}\nGenerated.esp\n',encoding='utf-8-sig')
            xml="""<config><moduleDependencies><fileDependency file="Generated.esp" state="Active"/></moduleDependencies><requiredInstallFiles><file source="Core.esp" destination="Core.esp"/></requiredInstallFiles></config>"""
            with zipfile.ZipFile(archive,'w') as z:z.writestr('fomod/ModuleConfig.xml',xml); z.writestr('Core.esp','plugin')
            plan=create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},root/'plans')
            self.assertEqual(plan['fomod_resolution']['environment']['file_states'],{'Generated.esp':'Active'})
            self.assertEqual(plan['fomod_resolution']['environment']['file_providers'],{'Generated.esp':['overwrite']})



    def test_fomod_comments_are_advisory_and_case_is_reported_faithfully(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); archive=root/'Comments.zip'
            xml='''<config><!-- <file source="Ignored.esp" destination="Ignored.esp"/> --><requiredInstallFiles><!-- around file --><file source="Core.esp" destination="Core.esp"/></requiredInstallFiles><!-- <pattern/> --></config>'''
            with zipfile.ZipFile(archive,'w') as z:
                z.writestr('Fomod/ModuleConfig.xml',xml); z.writestr('Core.esp','plugin'); z.writestr('Ignored.esp','ignored')
            descriptor=fomod_options(archive)
            self.assertEqual(descriptor['source'],'Fomod/ModuleConfig.xml')
            self.assertEqual(descriptor['canonical_source'],'fomod/ModuleConfig.xml')
            self.assertTrue(descriptor['case_variant'])
            preview=fomod_preview(archive,{'mo2_instance_path':str(instance),'profile':'Default'})
            warning=next(item for item in preview['validation_warnings'] if item['type']=='CommentsPresentWarning')
            self.assertTrue(warning['upstream_critical']); self.assertFalse(warning['critical']); self.assertFalse(warning['blocking']); self.assertTrue(warning['advisory'])
            self.assertEqual(preview['plugins'],['Core.esp'])
            self.assertNotIn('Ignored.esp',[Path(item['source']).name for item in preview['selected_files']])

    def test_selections_schema_and_unknown_ids_are_input_errors(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); archive=root/'Selections.zip'; self.archive(archive,True)
            cfg={'mo2_instance_path':str(instance),'profile':'Default'}
            invalid=['0:0',None,3,[],{'0:0':'0:0:0'},{'0:0':None},{'0:0':{}},{'0:0':[1]},{1:[]}]
            for index,value in enumerate(invalid):
                with self.subTest(value=value), self.assertRaises(WorkflowError) as caught:
                    create_plan(archive,cfg,root/f'plans-{index}',selections=value)
                self.assertEqual(caught.exception.code,2)
                self.assertIn('field',caught.exception.details); self.assertIn('expected',caught.exception.details); self.assertIn('actual',caught.exception.details); self.assertIn('example',caught.exception.details)
            with self.assertRaises(WorkflowError) as caught:
                create_plan(archive,cfg,root/'unknown-group',selections={'9:9':[]})
            self.assertEqual(caught.exception.code,2); self.assertEqual(caught.exception.details['unknown_groups'],['9:9'])
            with self.assertRaises(WorkflowError) as caught:
                create_plan(archive,cfg,root/'unknown-option',selections={'0:0':['0:0:9']})
            self.assertEqual(caught.exception.code,2); self.assertEqual(caught.exception.details['unknown_options'],{'0:0':['0:0:9']})
            plan=create_plan(archive,cfg,root/'valid',selections={'0:0':['0:0:0']})
            self.assertEqual(plan['selections'],{'0:0':['0:0:0']})

    def test_anchor_candidates_never_replace_exact_matching(self):
        lines=[HEADER,'+[NSFW] SLAL_SE','+Prefix SLAL_SE','+Unrelated']
        with self.assertRaises(WorkflowError) as caught:
            _place_mods(lines,['New'],{'after_mod':'SLAL_SE'})
        self.assertEqual(caught.exception.code,2)
        self.assertEqual(caught.exception.details['candidates'],[{'name':'[NSFW] SLAL_SE','reason':'tag_stripped_exact','line':2}])
        self.assertEqual(lines,[HEADER,'+[NSFW] SLAL_SE','+Prefix SLAL_SE','+Unrelated'])

    def test_auto_replan_applies_equivalent_unrelated_profile_drift(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'; archive=root/'Equivalent.zip'; self.archive(archive)
            plans=root/'plans'; plan=create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},plans)
            path=plans/f"{plan['id']}.json"
            text=(profile/'modlist.txt').read_text(encoding='utf-8-sig').replace('*DLC: Dawnguard','+Unrelated\n*DLC: Dawnguard')
            (profile/'modlist.txt').write_text(text,encoding='utf-8-sig',newline='\n')
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]):
                result=apply_plan(path,None,self.placement(),auto_replan=True)
            self.assertEqual(result['status'],'complete'); self.assertTrue(result['replan']['attempted']); self.assertTrue(result['replan']['equivalent'])
            self.assertNotEqual(result['replan']['original_plan_id'],result['replan']['effective_plan_id'])
            original=json.loads(path.read_text(encoding='utf-8'))
            self.assertEqual(original['status'],'superseded'); self.assertEqual(original['superseded_by'],result['id'])
            self.assertTrue((instance/'mods'/plan['mod_name']/'Test.esp').is_file())

    def test_auto_replan_requires_review_for_new_conflict_without_mo2_writes(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'; archive=root/'Conflict.zip'; self.archive(archive)
            plans=root/'plans'; plan=create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},plans); path=plans/f"{plan['id']}.json"
            provider=instance/'mods'/'New Provider'; provider.mkdir(); (provider/'Test.esp').write_text('conflict',encoding='utf-8')
            text=(profile/'modlist.txt').read_text(encoding='utf-8-sig').replace('*DLC: Dawnguard','+New Provider\n*DLC: Dawnguard')
            (profile/'modlist.txt').write_text(text,encoding='utf-8-sig',newline='\n')
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]), self.assertRaises(WorkflowError) as caught:
                apply_plan(path,None,self.placement(),auto_replan=True)
            self.assertEqual(caught.exception.code,1); self.assertEqual(caught.exception.details['status'],'replan_review_required')
            self.assertTrue(any(change['path'].startswith('$.conflict_file_providers') for change in caught.exception.details['semantic_changes']))
            self.assertTrue((plans/f"{caught.exception.details['new_plan_id']}.json").is_file())
            self.assertFalse((instance/'mods'/plan['mod_name']).exists()); self.assertFalse((instance/'_agent_toolkit_backups').exists())

    def test_auto_replan_anchor_loss_returns_review_with_candidates(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'; archive=root/'Anchor.zip'; self.archive(archive)
            plans=root/'plans'; plan=create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},plans); path=plans/f"{plan['id']}.json"
            text=(profile/'modlist.txt').read_text(encoding='utf-8-sig').replace('+'+SEPARATOR,'+[Generated] '+SEPARATOR)
            (profile/'modlist.txt').write_text(text,encoding='utf-8-sig',newline='\n')
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]), self.assertRaises(WorkflowError) as caught:
                apply_plan(path,None,self.placement(),auto_replan=True)
            self.assertEqual(caught.exception.code,1); review=caught.exception.details['placement_review']
            self.assertEqual(review['details']['candidates'][0]['reason'],'tag_stripped_exact')
            self.assertTrue((plans/f"{caught.exception.details['new_plan_id']}.json").is_file())
            self.assertFalse((instance/'_agent_toolkit_backups').exists())

    def test_equivalent_replan_failure_rolls_back_replacement_transaction(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'; archive=root/'RollbackReplan.zip'; self.archive(archive)
            plans=root/'plans'; plan=create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},plans); path=plans/f"{plan['id']}.json"
            text=(profile/'modlist.txt').read_text(encoding='utf-8-sig').replace('*DLC: Dawnguard','+Unrelated\n*DLC: Dawnguard')
            (profile/'modlist.txt').write_text(text,encoding='utf-8-sig',newline='\n'); current=(profile/'modlist.txt').read_bytes()
            failed={'status':'failed','checks':{'forced':False}}
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]), patch('mo2_agent_toolkit.workflow.audit_profile',return_value=failed), self.assertRaises(WorkflowError):
                apply_plan(path,None,self.placement(),auto_replan=True)
            original=json.loads(path.read_text(encoding='utf-8')); replacement=plans/f"{original['superseded_by']}.json"
            self.assertEqual(json.loads(replacement.read_text(encoding='utf-8'))['status'],'rolled_back')
            self.assertEqual((profile/'modlist.txt').read_bytes(),current); self.assertFalse((instance/'mods'/plan['mod_name']).exists())


    def test_auto_replan_reviews_operation_change(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'; archive=root/'Operation.zip'; self.archive(archive)
            plans=root/'plans'; plan=create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},plans); path=plans/f"{plan['id']}.json"
            target=instance/'mods'/plan['mod_name']; target.mkdir(); (target/'Old.esp').write_text('old',encoding='utf-8')
            text=(profile/'modlist.txt').read_text(encoding='utf-8-sig').replace('*DLC: Dawnguard',f"+{plan['mod_name']}\n*DLC: Dawnguard")
            (profile/'modlist.txt').write_text(text,encoding='utf-8-sig',newline='\n')
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]), self.assertRaises(WorkflowError) as caught:
                apply_plan(path,None,self.placement(),auto_replan=True)
            self.assertEqual(caught.exception.code,1)
            operation=next(change for change in caught.exception.details['semantic_changes'] if change['path']=='$.operation')
            self.assertEqual((operation['old'],operation['new']),('install','update'))
            self.assertEqual(json.loads((plans/f"{caught.exception.details['new_plan_id']}.json").read_text(encoding='utf-8'))['operation'],'update')
            self.assertFalse((instance/'_agent_toolkit_backups').exists())

    def test_auto_replan_reviews_update_adjacency_change(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'
            target=instance/'mods'/'Example'; target.mkdir(); (target/'Test.esp').write_text('old',encoding='utf-8')
            modlist=(profile/'modlist.txt').read_text(encoding='utf-8-sig').replace('+Ordinary Existing','+Example\n+Ordinary Existing')
            (profile/'modlist.txt').write_text(modlist,encoding='utf-8-sig',newline='\n')
            archive=root/'Example.zip'; self.archive(archive)
            plans=root/'plans'; plan=create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},plans); path=plans/f"{plan['id']}.json"
            self.assertEqual(plan['operation'],'update')
            changed=(profile/'modlist.txt').read_text(encoding='utf-8-sig').replace('+Example\n+Ordinary Existing','+Example\n+Inserted Neighbor\n+Ordinary Existing')
            (profile/'modlist.txt').write_text(changed,encoding='utf-8-sig',newline='\n')
            before=changed
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]), self.assertRaises(WorkflowError) as caught:
                apply_plan(path,None,auto_replan=True)
            self.assertEqual(caught.exception.code,1); self.assertEqual(caught.exception.details['status'],'replan_review_required')
            self.assertTrue(any(item['path'].endswith('.next_mod') for item in caught.exception.details['semantic_changes']))
            self.assertEqual((profile/'modlist.txt').read_text(encoding='utf-8-sig'),before)
            self.assertFalse((instance/'_agent_toolkit_backups').exists())

    def test_auto_replan_reviews_fomod_dependency_result_change(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'; game=root/'Game'; (game/'Data').mkdir(parents=True)
            archive=root/'DependencyChange.zip'
            xml='''<config><installSteps><installStep name="Choice"><optionalFileGroups><group name="Patch" type="SelectAny"><plugins><plugin name="Conditional"><files><file source="Patch.esp" destination="Patch.esp"/></files><typeDescriptor><dependencyType><defaultType name="Optional"/><patterns><pattern><dependencies><fileDependency file="Trigger.esp" state="Active"/></dependencies><type name="Recommended"/></pattern></patterns></dependencyType></typeDescriptor></plugin></plugins></group></optionalFileGroups></installStep></installSteps></config>'''
            with zipfile.ZipFile(archive,'w') as z:z.writestr('fomod/ModuleConfig.xml',xml); z.writestr('Patch.esp','plugin')
            cfg={'mo2_instance_path':str(instance),'profile':'Default','skyrim_game_path':str(game)}; plans=root/'plans'
            plan=create_plan(archive,cfg,plans,selections={'0:0':[]}); path=plans/f"{plan['id']}.json"
            provider=instance/'mods'/'Trigger Provider'; provider.mkdir(); (provider/'Trigger.esp').write_text('trigger',encoding='utf-8')
            text=(profile/'modlist.txt').read_text(encoding='utf-8-sig').replace('*DLC: Dawnguard','+Trigger Provider\n*DLC: Dawnguard')
            (profile/'modlist.txt').write_text(text,encoding='utf-8-sig',newline='\n')
            (profile/'plugins.txt').write_text(f'{HEADER}\n*Trigger.esp\n',encoding='utf-8-sig')
            (profile/'loadorder.txt').write_text(f'{HEADER}\nTrigger.esp\n',encoding='utf-8-sig')
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]), self.assertRaises(WorkflowError) as caught:
                apply_plan(path,None,self.placement(),auto_replan=True)
            self.assertEqual(caught.exception.code,1)
            self.assertTrue(any(change['path'].startswith('$.fomod_resolution') for change in caught.exception.details['semantic_changes']))
            self.assertFalse((instance/'_agent_toolkit_backups').exists())

    def test_auto_replan_does_not_bypass_archive_process_or_plan_state_safety(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/'profiles'/'Default'; archive=root/'Safety.zip'; self.archive(archive)
            plans=root/'plans'; cfg={'mo2_instance_path':str(instance),'profile':'Default'}
            plan=create_plan(archive,cfg,plans); path=plans/f"{plan['id']}.json"
            (profile/'modlist.txt').write_text((profile/'modlist.txt').read_text(encoding='utf-8-sig').replace('*DLC: Dawnguard','+Drift\n*DLC: Dawnguard'),encoding='utf-8-sig',newline='\n')
            with zipfile.ZipFile(archive,'a') as z:z.writestr('Changed.txt','changed')
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]), self.assertRaises(WorkflowError) as archive_error:
                apply_plan(path,None,self.placement(),auto_replan=True)
            self.assertEqual(archive_error.exception.code,2); self.assertEqual(len(list(plans.glob('*.json'))),1)
            self.archive(archive)
            plan=create_plan(archive,cfg,plans); path=plans/f"{plan['id']}.json"
            (profile/'modlist.txt').write_text((profile/'modlist.txt').read_text(encoding='utf-8-sig')+'+More Drift\n',encoding='utf-8-sig',newline='\n')
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=['ModOrganizer.exe']), self.assertRaises(WorkflowError) as process_error:
                apply_plan(path,None,self.placement(),auto_replan=True)
            self.assertEqual(process_error.exception.code,3); self.assertEqual(json.loads(path.read_text(encoding='utf-8'))['status'],'planned')
            data=json.loads(path.read_text(encoding='utf-8')); data['status']='complete'; path.write_text(json.dumps(data),encoding='utf-8')
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]), self.assertRaises(WorkflowError) as state_error:
                apply_plan(path,None,self.placement(),auto_replan=True)
            self.assertEqual(state_error.exception.code,2); self.assertEqual(json.loads(path.read_text(encoding='utf-8'))['status'],'complete')


    def test_data_folder_plan_and_apply_promotes_data_and_preserves_root_metadata(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); archive=root/"DataPackage.zip"
            with zipfile.ZipFile(archive,"w") as zipped:
                zipped.writestr("Data/Test.esp","plugin")
                zipped.writestr("Data/meshes/example.nif","mesh")
                zipped.writestr("README.txt","readme")
            plans=root/"plans"
            plan=create_plan(archive,{"mo2_instance_path":str(instance),"profile":"Default"},plans,name="Data Package")
            self.assertEqual(plan["handler"],"data-folder")
            with patch("mo2_agent_toolkit.workflow.mo2_running",return_value=[]):
                result=apply_plan(plans/f"{plan['id']}.json",None,self.placement())
            target=instance/"mods"/"Data Package"
            self.assertFalse((target/"Data").exists())
            self.assertTrue((target/"Test.esp").is_file())
            self.assertTrue((target/"meshes"/"example.nif").is_file())
            self.assertTrue((target/"README.txt").is_file())
            self.assertEqual(result["staged_validation"]["plugins"],["Test.esp"])

    def test_apply_blocks_newly_recognized_installer_risk_from_older_plan(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); archive=root/'Example.zip'
            with zipfile.ZipFile(archive,'w') as zipped:zipped.writestr('Example.esp','plugin')
            plans=root/'plans'; plan=create_plan(archive,{'mo2_instance_path':str(instance),'profile':'Default'},plans,name='Example')
            plan_path=plans/f"{plan['id']}.json"
            older=json.loads(plan_path.read_text(encoding='utf-8'))
            for key in ('handler','support_status','support_reason','installer_risk'):
                older['layout'].pop(key,None)
            plan_path.write_text(json.dumps(older),encoding='utf-8')
            risky=dict(plan['layout']); risky.update(handler='unsupported',support_status='risky',support_reason='executable_installer',installer_risk={'type':'executable_installer'})
            with patch('mo2_agent_toolkit.workflow.mo2_running',return_value=[]), patch('mo2_agent_toolkit.workflow.detect_layout',return_value=risky), self.assertRaises(WorkflowError) as caught:
                apply_plan(plan_path,None,self.placement())
            self.assertEqual(caught.exception.code,3)
            self.assertEqual(caught.exception.details['current_layout']['installer_risk']['type'],'executable_installer')
            self.assertFalse((instance/'_agent_toolkit_backups'/plan['id']).exists())

    def test_scripted_fomod_is_blocked_before_plan_creation(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); archive=root/"Scripted.zip"; plans=root/"plans"
            with zipfile.ZipFile(archive,"w") as zipped:
                zipped.writestr("fomod/ModuleConfig.xml","<config/>")
                zipped.writestr("fomod/Script.cs","public class Script {}")
                zipped.writestr("Test.esp","plugin")
            with self.assertRaises(WorkflowError) as caught:
                create_plan(archive,{"mo2_instance_path":str(instance),"profile":"Default"},plans,name="Scripted")
            self.assertEqual(caught.exception.code,3)
            self.assertEqual(caught.exception.details["risk"]["type"],"fomod_csharp")
            self.assertFalse(plans.exists())

    def test_archive_source_moves_mo2_meta_sidecar_with_archive(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); source=root/"Example.zip"; source.write_bytes(b"archive")
            sidecar=Path(str(source)+".meta"); sidecar.write_text("[General]\ninstalled=true\n",encoding="utf-8")
            result=archive_source(source,root/"archive")
            target=Path(result["path"]); target_meta=Path(str(target)+".meta")
            self.assertEqual(result["meta"]["status"],"moved")
            self.assertTrue(target.is_file()); self.assertTrue(target_meta.is_file())
            self.assertFalse(source.exists()); self.assertFalse(sidecar.exists())
            self.assertIn("installed=true",target_meta.read_text(encoding="utf-8"))

    def test_archive_source_preserves_different_sidecars_on_same_content_collision(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); destination=root/"archive"; destination.mkdir()
            target=destination/"Example.zip"; target.write_bytes(b"same")
            Path(str(target)+".meta").write_text("target",encoding="utf-8")
            source=root/"Example.zip"; source.write_bytes(b"same")
            Path(str(source)+".meta").write_text("source",encoding="utf-8")
            result=archive_source(source,destination,"123")
            moved=Path(result["path"]); moved_meta=Path(str(moved)+".meta")
            self.assertEqual(moved.name,"Example-123.zip")
            self.assertEqual(moved_meta.read_text(encoding="utf-8"),"source")
            self.assertEqual(Path(str(target)+".meta").read_text(encoding="utf-8"),"target")

    def test_archive_source_rolls_archive_back_when_sidecar_move_fails(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); destination=root/"archive"; source=root/"Example.zip"; source.write_bytes(b"archive")
            sidecar=Path(str(source)+".meta"); sidecar.write_text("meta",encoding="utf-8")
            original=shutil.move
            def fail_sidecar(src,dst,*args,**kwargs):
                if str(src).casefold().endswith(".meta"):raise OSError("sidecar denied")
                return original(src,dst,*args,**kwargs)
            with patch("mo2_agent_toolkit.workflow.shutil.move",side_effect=fail_sidecar),self.assertRaises(OSError):
                archive_source(source,destination)
            self.assertTrue(source.is_file()); self.assertTrue(sidecar.is_file())
            self.assertFalse((destination/"Example.zip").exists())


if __name__ == "__main__":
    unittest.main()
