import json
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest.mock import patch

from mo2_agent_toolkit import cli
from mo2_agent_toolkit.workflow import (
    WorkflowError,
    _list_7z,
    _place_mods,
    apply_plan,
    collect_batch,
    create_plan,
    prepare_batch,
    archive_source,
)

SEPARATOR = "—————— 其他模组生成 ——————_separator"
HEADER = "# This file was automatically generated by Mod Organizer."


class WorkflowTests(unittest.TestCase):
    def instance(self, root: Path) -> Path:
        instance = root / "MO2"
        for name in cli.REQUIRED_DIRS:
            (instance / name).mkdir(parents=True, exist_ok=True)
        profile = instance / "profiles" / "Default"
        profile.mkdir(parents=True)
        (profile / "modlist.txt").write_text(
            f"{HEADER}\n+{SEPARATOR}\n+Ordinary Existing\n*DLC: Dawnguard\n",
            encoding="utf-8-sig",
        )
        (profile / "plugins.txt").write_text(f"{HEADER}\n", encoding="utf-8-sig")
        (profile / "loadorder.txt").write_text(f"{HEADER}\n", encoding="utf-8-sig")
        return instance

    def archive(self, path: Path, fomod: bool = False) -> None:
        with zipfile.ZipFile(path, "w") as archive:
            archive.writestr("Wrapper/Test.esp", "x")
            archive.writestr("Wrapper/SKSE/Plugins/test.dll", "x")
            if fomod:
                archive.writestr(
                    "Wrapper/fomod/ModuleConfig.xml",
                    '<config><requiredInstallFiles><file source="Test.esp" destination="Test.esp"/></requiredInstallFiles>'
                    '<installSteps><installStep name="Options"><optionalFileGroups><group name="Patch" type="SelectAny">'
                    '<plugins><plugin name="Optional"><files><folder source="SKSE" destination="SKSE"/></files>'
                    '<typeDescriptor><type name="Optional"/></typeDescriptor></plugin></plugins></group>'
                    '</optionalFileGroups></installStep></installSteps></config>',
                )

    def placement(self) -> dict:
        return {"after_mod": SEPARATOR}

    def test_7z_listing_excludes_archive_header_record(self):
        listing = """Path = C:\\Downloads\\Example.rar
Type = Rar

----------
Path = Data\\Example.esp
Size = 1
Packed Size = 1
Attributes = A
"""
        completed = type("Result", (), {"returncode": 0, "stdout": listing, "stderr": ""})()
        with patch("mo2_agent_toolkit.workflow.subprocess.run", return_value=completed):
            entries = _list_7z(Path(r"C:\Downloads\Example.rar"), "7z.exe")
        self.assertEqual([item["Path"] for item in entries], [r"Data\Example.esp"])

    def test_plan_reports_layout_context_and_requires_placement(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Elegant.zip"; self.archive(archive)
            provider = instance / "mods" / "Ordinary Existing"; provider.mkdir(); (provider / "Test.esp").write_text("old", encoding="utf-8")
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            self.assertEqual(plan["layout"]["nesting_root"], "Wrapper")
            self.assertTrue(plan["layout"]["flatten"])
            self.assertTrue(plan["placement"]["required"])
            self.assertIn(SEPARATOR, [item["name"] for item in plan["modlist_context"]["separators"]])
            self.assertEqual(plan["modlist_context"]["conflict_file_providers"][0]["mod"], "Ordinary Existing")

    def test_duplicate_anchor_is_rejected_before_any_deduplication(self):
        lines = [HEADER, "+Anchor", "-Anchor", "+Other"]
        with self.assertRaises(WorkflowError) as caught:
            _place_mods(lines, ["New"], {"after_mod": "Anchor"})
        self.assertIn("duplicated", str(caught.exception))

    def test_apply_flattens_then_rescans_plugins_and_places_after_separator(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]):
                result = apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            target = instance / "mods" / plan["mod_name"]
            self.assertTrue((target / "Test.esp").exists())
            self.assertFalse((target / "Wrapper").exists())
            self.assertEqual(result["plugins_enabled"], ["Test.esp"])
            lines = (instance / "profiles" / "Default" / "modlist.txt").read_text(encoding="utf-8-sig").splitlines()
            self.assertEqual(lines.index("+" + plan["mod_name"]), lines.index("+" + SEPARATOR) + 1)
            self.assertEqual(result["final_placement"]["file_direction"]["previous_mod"], SEPARATOR)

    def test_invalid_staged_root_is_rejected_before_commit(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Invalid.zip"
            with zipfile.ZipFile(archive, "w") as zipped:
                zipped.writestr("Wrapper/docs/manual.bin", "x")
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            original = (instance / "profiles" / "Default" / "modlist.txt").read_bytes()
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]):
                with self.assertRaises(WorkflowError) as caught:
                    apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            self.assertIn("current_root_entries", caught.exception.details)
            self.assertIn("Wrapper", caught.exception.details["suspected_wrapper_directories"])
            self.assertFalse((instance / "mods" / plan["mod_name"]).exists())
            self.assertEqual((instance / "profiles" / "Default" / "modlist.txt").read_bytes(), original)

    def test_missing_anchor_stops_without_highest_priority_fallback(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]):
                with self.assertRaises(WorkflowError) as caught:
                    apply_plan(root / "plans" / f"{plan['id']}.json", None, {"after_mod": "Missing"})
            self.assertIn("missing", str(caught.exception))
            self.assertFalse((instance / "_agent_toolkit_backups" / plan["id"]).exists())

    def test_failure_restores_old_mod_and_all_profile_files(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            old = instance / "mods" / "Example"; old.mkdir(); (old / "old.txt").write_text("old", encoding="utf-8")
            profile = instance / "profiles" / "Default"
            modlist = (profile / "modlist.txt").read_text(encoding="utf-8-sig").replace("+Ordinary Existing", "+Example\n+Ordinary Existing")
            (profile / "modlist.txt").write_text(modlist, encoding="utf-8-sig", newline="\n")
            originals = {name: (profile / name).read_bytes() for name in ("modlist.txt", "plugins.txt", "loadorder.txt")}
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            failed = {"status": "failed", "issues": [{"severity": "error", "what": "forced"}]}
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]), patch("mo2_agent_toolkit.workflow.audit_profile", return_value=failed):
                with self.assertRaises(WorkflowError):
                    apply_plan(root / "plans" / f"{plan['id']}.json", None)
            self.assertEqual((old / "old.txt").read_text(encoding="utf-8"), "old")
            for name, content in originals.items():
                self.assertEqual((profile / name).read_bytes(), content)

    def test_multiple_mods_keep_high_to_low_order_and_untouched_order(self):
        lines = [HEADER, "+High", "+" + SEPARATOR, "+Ordinary A", "+Ordinary B"]
        updated, _ = _place_mods(lines, ["New High", "New Low"], {"after_mod": SEPARATOR})
        self.assertEqual(updated, [HEADER, "+High", "+" + SEPARATOR, "+New High", "+New Low", "+Ordinary A", "+Ordinary B"])

    def test_apply_blocks_while_mo2_runs(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "A.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=["ModOrganizer.exe"]):
                with self.assertRaises(WorkflowError) as caught:
                    apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            self.assertEqual(caught.exception.code, 3)

    def test_fomod_requires_explicit_selections(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Fomod.zip"; self.archive(archive, True)
            with self.assertRaises(WorkflowError) as caught:
                create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            self.assertEqual(caught.exception.code, 1)
            self.assertEqual(caught.exception.details["layout"]["nesting_root"], "Wrapper")

    def test_archive_failure_is_post_commit_warning(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default", "archive_after_install": True, "archive_directory": str(root / "archive")}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]), patch("mo2_agent_toolkit.workflow.archive_source", side_effect=OSError("denied")):
                result = apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            self.assertEqual(result["status"], "installed_with_warnings")
            self.assertTrue((instance / "mods" / plan["mod_name"]).is_dir())

    def test_update_preserves_position_enable_state_and_disables_new_plugin(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/"profiles"/"Default"
            target=instance/"mods"/"Example"; target.mkdir(); (target/"Old.esp").write_text("old",encoding="utf-8"); (target/"Removed.esp").write_text("old",encoding="utf-8")
            (target/"meta.ini").write_text("[General]\ncategory=42\nversion=1.0\n",encoding="utf-8")
            modlist=(profile/"modlist.txt").read_text(encoding="utf-8-sig").replace("+Ordinary Existing","-Example\n+Ordinary Existing")
            (profile/"modlist.txt").write_text(modlist,encoding="utf-8-sig",newline="\n")
            (profile/"plugins.txt").write_text(f"{HEADER}\n*Old.esp\n*Removed.esp\n",encoding="utf-8-sig")
            (profile/"loadorder.txt").write_text(f"{HEADER}\nOld.esp\nRemoved.esp\n",encoding="utf-8-sig")
            archive=root/"Example.zip"
            with zipfile.ZipFile(archive,"w") as z:
                z.writestr("Old.esp","new"); z.writestr("New.esp","new")
            source={"provider":"nexus","mod_id":133568,"file_id":751019,"official_filename":"Example Official.zip","version":"1.0.9","last_modified":"2026-05-11T10:06:29Z"}
            plan=create_plan(archive,{"mo2_instance_path":str(instance),"profile":"Default"},root/"plans",source_metadata=source)
            self.assertEqual(plan["operation"],"update"); self.assertFalse(plan["placement"]["required"])
            with patch("mo2_agent_toolkit.workflow.mo2_running",return_value=[]):
                result=apply_plan(root/"plans"/f"{plan['id']}.json",None)
            self.assertIn("-Example",(profile/"modlist.txt").read_text(encoding="utf-8-sig").splitlines())
            plugin_lines=(profile/"plugins.txt").read_text(encoding="utf-8-sig").splitlines()
            self.assertIn("*Old.esp",plugin_lines); self.assertIn("New.esp",plugin_lines); self.assertNotIn("*New.esp",plugin_lines); self.assertNotIn("*Removed.esp",plugin_lines)
            self.assertNotIn("Removed.esp",(profile/"loadorder.txt").read_text(encoding="utf-8-sig").splitlines())
            self.assertEqual(result["plugin_changes"]["new_plugins_disabled"],["New.esp"]); self.assertEqual(result["plugin_changes"]["removed_plugins"],["Removed.esp"])
            self.assertEqual(result["content_audit"]["status"],"passed")
            meta=(target/"meta.ini").read_text(encoding="utf-8-sig")
            self.assertIn("category=42",meta); self.assertIn(r"1\fileid=751019",meta); self.assertNotIn("\f",meta)

    def test_update_rejects_state_drift_before_transaction(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/"profiles"/"Default"
            target=instance/"mods"/"Example"; target.mkdir(); (target/"Test.esp").write_text("old",encoding="utf-8")
            modlist=(profile/"modlist.txt").read_text(encoding="utf-8-sig").replace("+Ordinary Existing","+Example\n+Ordinary Existing")
            (profile/"modlist.txt").write_text(modlist,encoding="utf-8-sig",newline="\n")
            archive=root/"Example.zip"; self.archive(archive)
            plan=create_plan(archive,{"mo2_instance_path":str(instance),"profile":"Default"},root/"plans")
            changed=(profile/"modlist.txt").read_text(encoding="utf-8-sig").replace("+Example","-Example")
            (profile/"modlist.txt").write_text(changed,encoding="utf-8-sig",newline="\n")
            with patch("mo2_agent_toolkit.workflow.mo2_running",return_value=[]),self.assertRaises(WorkflowError):
                apply_plan(root/"plans"/f"{plan['id']}.json",None)
            self.assertFalse((instance/"_agent_toolkit_backups"/plan["id"]).exists())

    def test_archive_source_same_path_is_safe_noop(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); source=root/"Example.zip"; source.write_bytes(b"archive")
            result=archive_source(source,root)
            self.assertEqual(result["status"],"already_in_archive"); self.assertTrue(source.exists())


    def test_batch_collect_by_file_id(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); (root / "CoolMod-12345.zip").write_bytes(b"x")
            data = prepare_batch(10, [12345], root, root / "sessions", False)
            result = collect_batch(root / "sessions" / f"{data['id']}.json")
            self.assertEqual(result["status"], "collected")



    def test_plan_rejects_malformed_nexus_source_metadata(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); archive=root/"Example.zip"; self.archive(archive)
            cfg={"mo2_instance_path":str(instance),"profile":"Default"}
            bad={"provider":"nexus","mod_id":133568,"file_id":751019,"official_filename":"../bad.zip","version":"1.0.9"}
            with self.assertRaises(WorkflowError) as caught:
                create_plan(archive,cfg,root/"plans",source_metadata=bad)
            self.assertIn("safe Windows basename",str(caught.exception))

    def test_content_audit_failure_rolls_back_mod_and_profile(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); instance=self.instance(root); profile=instance/"profiles"/"Default"
            target=instance/"mods"/"Example"; target.mkdir(); (target/"Old.esp").write_text("old",encoding="utf-8")
            original={name:(profile/name).read_bytes() for name in ("modlist.txt","plugins.txt","loadorder.txt")}
            modlist=(profile/"modlist.txt").read_text(encoding="utf-8-sig").replace("+Ordinary Existing","+Example\n+Ordinary Existing")
            (profile/"modlist.txt").write_text(modlist,encoding="utf-8-sig",newline="\n")
            original={name:(profile/name).read_bytes() for name in ("modlist.txt","plugins.txt","loadorder.txt")}
            archive=root/"Example.zip"; self.archive(archive)
            plan=create_plan(archive,{"mo2_instance_path":str(instance),"profile":"Default"},root/"plans")
            failed={"status":"failed","expected_files":2,"installed_files":1,"missing":["Test.esp"],"extra":[],"different":[]}
            with patch("mo2_agent_toolkit.workflow.mo2_running",return_value=[]), patch("mo2_agent_toolkit.workflow._compare_manifests",return_value=failed), self.assertRaises(WorkflowError):
                apply_plan(root/"plans"/f"{plan['id']}.json",None)
            self.assertEqual((target/"Old.esp").read_text(encoding="utf-8"),"old")
            for name,content in original.items():self.assertEqual((profile/name).read_bytes(),content)
            rolled=json.loads((root/"plans"/f"{plan['id']}.json").read_text(encoding="utf-8"))
            self.assertEqual(rolled["status"],"rolled_back")

    def test_archive_source_uses_unique_collision_suffix(self):
        with tempfile.TemporaryDirectory() as temp:
            root=Path(temp); source_dir=root/"source"; destination=root/"archive"
            source_dir.mkdir(); destination.mkdir(); source=source_dir/"Example.zip"; source.write_bytes(b"new")
            (destination/"Example.zip").write_bytes(b"old"); (destination/"Example-42.zip").write_bytes(b"older")
            result=archive_source(source,destination,"42")
            self.assertEqual(Path(result["path"]).name,"Example-42-2.zip")
            self.assertEqual(Path(result["path"]).read_bytes(),b"new")


if __name__ == "__main__":
    unittest.main()
