import json
import tempfile
import unittest
import zipfile
from pathlib import Path
from unittest.mock import patch

from mo2_agent_toolkit import cli
from mo2_agent_toolkit.workflow import (
    WorkflowError,
    _list_7z,
    _place_mods,
    apply_plan,
    collect_batch,
    create_plan,
    prepare_batch,
)

SEPARATOR = "—————— 其他模组生成 ——————_separator"
HEADER = "# This file was automatically generated by Mod Organizer."


class WorkflowTests(unittest.TestCase):
    def instance(self, root: Path) -> Path:
        instance = root / "MO2"
        for name in cli.REQUIRED_DIRS:
            (instance / name).mkdir(parents=True, exist_ok=True)
        profile = instance / "profiles" / "Default"
        profile.mkdir(parents=True)
        (profile / "modlist.txt").write_text(
            f"{HEADER}\n+{SEPARATOR}\n+Ordinary Existing\n*DLC: Dawnguard\n",
            encoding="utf-8-sig",
        )
        (profile / "plugins.txt").write_text(f"{HEADER}\n", encoding="utf-8-sig")
        (profile / "loadorder.txt").write_text(f"{HEADER}\n", encoding="utf-8-sig")
        return instance

    def archive(self, path: Path, fomod: bool = False) -> None:
        with zipfile.ZipFile(path, "w") as archive:
            archive.writestr("Wrapper/Test.esp", "x")
            archive.writestr("Wrapper/SKSE/Plugins/test.dll", "x")
            if fomod:
                archive.writestr(
                    "Wrapper/fomod/ModuleConfig.xml",
                    '<config><requiredInstallFiles><file source="Test.esp" destination="Test.esp"/></requiredInstallFiles>'
                    '<installSteps><installStep name="Options"><optionalFileGroups><group name="Patch" type="SelectAny">'
                    '<plugins><plugin name="Optional"><files><folder source="SKSE" destination="SKSE"/></files>'
                    '<typeDescriptor><type name="Optional"/></typeDescriptor></plugin></plugins></group>'
                    '</optionalFileGroups></installStep></installSteps></config>',
                )

    def placement(self) -> dict:
        return {"after_mod": SEPARATOR}

    def test_7z_listing_excludes_archive_header_record(self):
        listing = """Path = C:\\Downloads\\Example.rar
Type = Rar

----------
Path = Data\\Example.esp
Size = 1
Packed Size = 1
Attributes = A
"""
        completed = type("Result", (), {"returncode": 0, "stdout": listing, "stderr": ""})()
        with patch("mo2_agent_toolkit.workflow.subprocess.run", return_value=completed):
            entries = _list_7z(Path(r"C:\Downloads\Example.rar"), "7z.exe")
        self.assertEqual([item["Path"] for item in entries], [r"Data\Example.esp"])

    def test_plan_reports_layout_context_and_requires_placement(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Elegant.zip"; self.archive(archive)
            provider = instance / "mods" / "Ordinary Existing"; provider.mkdir(); (provider / "Test.esp").write_text("old", encoding="utf-8")
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            self.assertEqual(plan["layout"]["nesting_root"], "Wrapper")
            self.assertTrue(plan["layout"]["flatten"])
            self.assertTrue(plan["placement"]["required"])
            self.assertIn(SEPARATOR, [item["name"] for item in plan["modlist_context"]["separators"]])
            self.assertEqual(plan["modlist_context"]["conflict_file_providers"][0]["mod"], "Ordinary Existing")

    def test_duplicate_anchor_is_rejected_before_any_deduplication(self):
        lines = [HEADER, "+Anchor", "-Anchor", "+Other"]
        with self.assertRaises(WorkflowError) as caught:
            _place_mods(lines, ["New"], {"after_mod": "Anchor"})
        self.assertIn("duplicated", str(caught.exception))

    def test_apply_flattens_then_rescans_plugins_and_places_after_separator(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]):
                result = apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            target = instance / "mods" / plan["mod_name"]
            self.assertTrue((target / "Test.esp").exists())
            self.assertFalse((target / "Wrapper").exists())
            self.assertEqual(result["plugins_enabled"], ["Test.esp"])
            lines = (instance / "profiles" / "Default" / "modlist.txt").read_text(encoding="utf-8-sig").splitlines()
            self.assertEqual(lines.index("+" + plan["mod_name"]), lines.index("+" + SEPARATOR) + 1)
            self.assertEqual(result["final_placement"]["file_direction"]["previous_mod"], SEPARATOR)

    def test_invalid_staged_root_is_rejected_before_commit(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Invalid.zip"
            with zipfile.ZipFile(archive, "w") as zipped:
                zipped.writestr("Wrapper/docs/manual.bin", "x")
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            original = (instance / "profiles" / "Default" / "modlist.txt").read_bytes()
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]):
                with self.assertRaises(WorkflowError) as caught:
                    apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            self.assertIn("current_root_entries", caught.exception.details)
            self.assertIn("Wrapper", caught.exception.details["suspected_wrapper_directories"])
            self.assertFalse((instance / "mods" / plan["mod_name"]).exists())
            self.assertEqual((instance / "profiles" / "Default" / "modlist.txt").read_bytes(), original)

    def test_missing_anchor_stops_without_highest_priority_fallback(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]):
                with self.assertRaises(WorkflowError) as caught:
                    apply_plan(root / "plans" / f"{plan['id']}.json", None, {"after_mod": "Missing"})
            self.assertIn("missing", str(caught.exception))
            self.assertFalse((instance / "_agent_toolkit_backups" / plan["id"]).exists())

    def test_failure_restores_old_mod_and_all_profile_files(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            old = instance / "mods" / "Example"; old.mkdir(); (old / "old.txt").write_text("old", encoding="utf-8")
            profile = instance / "profiles" / "Default"
            originals = {name: (profile / name).read_bytes() for name in ("modlist.txt", "plugins.txt", "loadorder.txt")}
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            failed = {"status": "failed", "issues": [{"severity": "error", "what": "forced"}]}
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]), patch("mo2_agent_toolkit.workflow.audit_profile", return_value=failed):
                with self.assertRaises(WorkflowError):
                    apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            self.assertEqual((old / "old.txt").read_text(encoding="utf-8"), "old")
            for name, content in originals.items():
                self.assertEqual((profile / name).read_bytes(), content)

    def test_multiple_mods_keep_high_to_low_order_and_untouched_order(self):
        lines = [HEADER, "+High", "+" + SEPARATOR, "+Ordinary A", "+Ordinary B"]
        updated, _ = _place_mods(lines, ["New High", "New Low"], {"after_mod": SEPARATOR})
        self.assertEqual(updated, [HEADER, "+High", "+" + SEPARATOR, "+New High", "+New Low", "+Ordinary A", "+Ordinary B"])

    def test_apply_blocks_while_mo2_runs(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "A.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=["ModOrganizer.exe"]):
                with self.assertRaises(WorkflowError) as caught:
                    apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            self.assertEqual(caught.exception.code, 3)

    def test_fomod_requires_explicit_selections(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Fomod.zip"; self.archive(archive, True)
            with self.assertRaises(WorkflowError) as caught:
                create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default"}, root / "plans")
            self.assertEqual(caught.exception.code, 1)
            self.assertEqual(caught.exception.details["layout"]["nesting_root"], "Wrapper")

    def test_archive_failure_is_post_commit_warning(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); instance = self.instance(root); archive = root / "Example.zip"; self.archive(archive)
            plan = create_plan(archive, {"mo2_instance_path": str(instance), "profile": "Default", "archive_after_install": True, "archive_directory": str(root / "archive")}, root / "plans")
            with patch("mo2_agent_toolkit.workflow.mo2_running", return_value=[]), patch("mo2_agent_toolkit.workflow.archive_source", side_effect=OSError("denied")):
                result = apply_plan(root / "plans" / f"{plan['id']}.json", None, self.placement())
            self.assertEqual(result["status"], "installed_with_warnings")
            self.assertTrue((instance / "mods" / plan["mod_name"]).is_dir())

    def test_batch_collect_by_file_id(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp); (root / "CoolMod-12345.zip").write_bytes(b"x")
            data = prepare_batch(10, [12345], root, root / "sessions", False)
            result = collect_batch(root / "sessions" / f"{data['id']}.json")
            self.assertEqual(result["status"], "collected")


if __name__ == "__main__":
    unittest.main()
