import contextlib
import io
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

from mo2_agent_toolkit import cli

class CliTests(unittest.TestCase):
    def make_instance(self, root: Path, profile="Default") -> Path:
        instance=root/"中文 MO2 [Test]"
        for name in cli.REQUIRED_DIRS: (instance/name).mkdir(parents=True,exist_ok=True)
        p=instance/"profiles"/profile; p.mkdir(parents=True)
        (p/"modlist.txt").write_text("# This file was automatically generated by Mod Organizer.\n+—————— 其他模组生成 ——————_separator\n*DLC: Dawnguard\n",encoding="utf-8-sig")
        (p/"plugins.txt").write_text("# header\n",encoding="utf-8")
        (p/"loadorder.txt").write_text("# header\n",encoding="utf-8")
        return instance

    def test_instance_and_profiles_support_unicode(self):
        with tempfile.TemporaryDirectory() as td:
            instance=self.make_instance(Path(td))
            self.assertTrue(cli.valid_instance(instance))
            self.assertEqual(cli.profiles(instance),["Default"])

    def test_setup_writes_external_config(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); instance=self.make_instance(base); config=base/"local"/"config.toml"
            with patch.object(cli,"CONFIG_PATH",config):
                out=io.StringIO()
                with contextlib.redirect_stdout(out):
                    code=cli.main(["setup","--instance",str(instance),"--profile","Default","--json"])
                self.assertEqual(code,0); self.assertTrue(config.exists())
                parsed=cli.load_config(config)
                self.assertEqual(Path(parsed["mo2_instance_path"]),instance.resolve())
                self.assertEqual(json.loads(out.getvalue())["schema_version"],1)

    def test_setup_dry_run_does_not_write(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); instance=self.make_instance(base); config=base/"config.toml"
            with patch.object(cli,"CONFIG_PATH",config):
                code=cli.main(["setup","--instance",str(instance),"--profile","Default","--dry-run","--json"])
                self.assertEqual(code,0); self.assertFalse(config.exists())

    def test_doctor_warns_without_config(self):
        with tempfile.TemporaryDirectory() as td:
            out=io.StringIO()
            with patch.object(cli,"CONFIG_PATH",Path(td)/"missing.toml"), contextlib.redirect_stdout(out):
                code=cli.main(["doctor","--json"])
            self.assertEqual(code,1)
            payload=json.loads(out.getvalue())
            self.assertEqual(payload["status"],"warning")
            self.assertFalse(payload["data"]["checks"]["config_exists"])

    def test_backup_rejects_escape(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); instance=self.make_instance(base); config=base/"config.toml"
            cli.save_config({"mo2_instance_path":str(instance),"profile":"Default"},config)
            with patch.object(cli,"CONFIG_PATH",config):
                out=io.StringIO()
                with contextlib.redirect_stdout(out): code=cli.main(["backup","inspect","..","--json"])
            self.assertEqual(code,2)

    def test_profile_apply_creates_restorable_transaction(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); instance=self.make_instance(base); config=base/"config.toml"
            mod=instance/"mods"/"Example Mod"; mod.mkdir()
            cli.save_config({"mo2_instance_path":str(instance),"profile":"Default"},config)
            original=(instance/"profiles"/"Default"/"modlist.txt").read_bytes()
            with patch.object(cli,"CONFIG_PATH",config), patch.dict("os.environ",{"MO2_PROFILE_UPDATE_ALLOW_RUNNING":"1"}):
                code=cli.main(["profile","apply","Default","--enable-mod","Example Mod","--after-mod","—————— 其他模组生成 ——————_separator"])
                self.assertEqual(code,0)
                self.assertIn("+Example Mod",(instance/"profiles"/"Default"/"modlist.txt").read_text(encoding="utf-8-sig"))
                backups=instance/"_agent_toolkit_backups"
                tx=next(backups.iterdir())
                manifest=json.loads((tx/"manifest.json").read_text(encoding="utf-8"))
                self.assertEqual(manifest["status"],"complete")
                self.assertEqual(manifest["operation"],"profile_apply")
                code=cli.main(["backup","restore",tx.name,"--yes","--json"])
                self.assertEqual(code,0)
                self.assertEqual((instance/"profiles"/"Default"/"modlist.txt").read_bytes(),original)

    def test_install_help_lists_transactional_subcommands(self):
        out=io.StringIO()
        with contextlib.redirect_stdout(out):
            with self.assertRaises(SystemExit) as caught: cli.main(["install","--help"])
        self.assertEqual(caught.exception.code,0)
        for command in ("inspect","plan","apply","resume"):
            self.assertIn(command,out.getvalue())

    def test_install_flags_after_archive_are_promoted(self):
        with patch.object(cli, "run_legacy", return_value=0) as run:
            code = cli.main(["install", "Example Mod.zip", "--dry-run", "--json"])
        self.assertEqual(code, 0)
        self.assertEqual(run.call_args.args[0], "mod-install.py")
        self.assertEqual(run.call_args.args[1], ["dry-run", "Example Mod.zip", "--json"])

    def test_nexus_request_waits_for_stable_archive_and_recommends_dry_run(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); instance=self.make_instance(base); config=base/"config.toml"
            cli.save_config({"mo2_instance_path":str(instance),"profile":"Default"},config)
            downloads=instance/"downloads"; target=downloads/"Example Mod-123-456.zip"
            metadata={"mod_id":123,"file_id":456,"file_name":target.name,"version":"1.0","category_name":"MAIN","expected_size_bytes":2048}
            calls={"sleep":0}
            def fake_sleep(_seconds):
                calls["sleep"]+=1
                if calls["sleep"]==1: target.write_bytes(b"x"*2048)
            layout={"type":"mo2","has_nesting":False,"has_fomod":False,"has_root_files":False,"plugin_count":1}
            with patch.object(cli,"CONFIG_PATH",config), patch.object(cli,"default_browser_downloads_dir",return_value=downloads), patch.object(cli,"_nexus_file_metadata",return_value=metadata), patch.object(cli,"open_browser_tab",return_value=True), patch.object(cli,"_test_and_inspect_archive",return_value=layout), patch.object(cli.time,"sleep",side_effect=fake_sleep):
                out=io.StringIO()
                with contextlib.redirect_stdout(out): code=cli.main(["nexus","request","123","456","--timeout","5","--poll-interval","0","--json"])
            payload=json.loads(out.getvalue())
            self.assertEqual(code,0); self.assertEqual(payload["data"]["status"],"verified")
            self.assertIn("install",payload["data"]["recommended_commands"][0])
            self.assertIn("install inspect",payload["data"]["recommended_commands"][0])
            self.assertIn("--modid 123 --file-id 456",payload["data"]["recommended_commands"][1])

    def test_nexus_request_no_wait_returns_manual_url(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); instance=self.make_instance(base); config=base/"config.toml"
            cli.save_config({"mo2_instance_path":str(instance),"profile":"Default"},config)
            metadata={"mod_id":123,"file_id":456,"file_name":"Example.zip","version":"1","category_name":"MAIN","expected_size_bytes":1000}
            with patch.object(cli,"CONFIG_PATH",config), patch.object(cli,"default_browser_downloads_dir",return_value=instance/"downloads"), patch.object(cli,"_nexus_file_metadata",return_value=metadata), patch.object(cli,"open_browser_tab",return_value=True):
                out=io.StringIO()
                with contextlib.redirect_stdout(out): code=cli.main(["nexus","request","123","456","--no-wait","--json"])
            self.assertEqual(code,1); self.assertFalse(json.loads(out.getvalue())["data"]["waiting"])

    def test_browser_downloads_falls_back_to_home_downloads(self):
        with tempfile.TemporaryDirectory() as td, patch("winreg.OpenKey",side_effect=OSError), patch.object(cli.Path,"home",return_value=Path(td)):
            self.assertEqual(cli.default_browser_downloads_dir(),(Path(td)/"Downloads").resolve())

    def test_candidate_rejects_wrong_size_and_partial_files(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); metadata={"mod_id":123,"file_id":456,"file_name":"Example.zip","expected_size_bytes":10000}
            partial=base/"Example.zip.crdownload"; partial.write_bytes(b"x"*10000)
            wrong=base/"Example.zip"; wrong.write_bytes(b"x"*100)
            self.assertEqual(cli._candidate_score(partial,metadata),-1)
            self.assertEqual(cli._candidate_score(wrong,metadata),-1)

    def test_recommendation_routes_root_package(self):
        commands=cli._recommended_download_commands(Path(r"C:\Downloads\SKSE.zip"),{"type":"root"})
        self.assertIn("root inspect",commands[0]); self.assertIn("root deploy",commands[1])

    def test_root_inspect_recognizes_skse_without_writing(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); instance=self.make_instance(base); game=base/"game"; game.mkdir()
            (game/"SkyrimSE.exe").write_bytes(b"game")
            content=base/"content"; content.mkdir()
            (content/"skse64_loader.exe").write_bytes(b"loader")
            (content/"skse64_1_6_1170.dll").write_bytes(b"dll")
            archive=base/"skse.zip"; archive.write_bytes(b"archive")
            config=base/"config.toml"
            cli.save_config({"mo2_instance_path":str(instance),"profile":"Default","skyrim_game_path":str(game)},config)
            with patch.object(cli,"CONFIG_PATH",config), patch.object(cli,"_extract_root_archive",return_value=content):
                out=io.StringIO()
                with contextlib.redirect_stdout(out): code=cli.main(["root","inspect",str(archive),"--json"])
            payload=json.loads(out.getvalue())
            self.assertEqual(code,1); self.assertEqual(payload["data"]["package_type"],"skse")
            self.assertFalse((game/"skse64_loader.exe").exists())

    def test_root_deploy_backs_up_and_restores_engine_fixes(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); instance=self.make_instance(base); game=base/"game"; game.mkdir()
            (game/"SkyrimSE.exe").write_bytes(b"game")
            (game/"d3dx9_42.dll").write_bytes(b"old")
            content=base/"content"; content.mkdir()
            (content/"d3dx9_42.dll").write_bytes(b"new")
            (content/"tbb.dll").write_bytes(b"tbb")
            archive=base/"engine-fixes.zip"; archive.write_bytes(b"archive")
            config=base/"config.toml"
            cli.save_config({"mo2_instance_path":str(instance),"profile":"Default","skyrim_game_path":str(game)},config)
            with patch.object(cli,"CONFIG_PATH",config), patch.object(cli,"_extract_root_archive",return_value=content), patch.object(cli,"_game_processes_running",return_value=[]):
                out=io.StringIO()
                with contextlib.redirect_stdout(out): code=cli.main(["root","deploy",str(archive),"--yes","--json"])
                payload=json.loads(out.getvalue()); backup_id=payload["data"]["backup_id"]
                self.assertEqual(code,0); self.assertEqual((game/"d3dx9_42.dll").read_bytes(),b"new")
                code=cli.main(["backup","restore",backup_id,"--yes","--json"])
            self.assertEqual(code,0); self.assertEqual((game/"d3dx9_42.dll").read_bytes(),b"old")
            self.assertFalse((game/"tbb.dll").exists())

    def test_root_deploy_rejects_unknown_package(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); instance=self.make_instance(base); game=base/"game"; game.mkdir()
            (game/"SkyrimSE.exe").write_bytes(b"game")
            content=base/"content"; content.mkdir(); (content/"unknown.dll").write_bytes(b"x")
            archive=base/"unknown.zip"; archive.write_bytes(b"archive")
            config=base/"config.toml"
            cli.save_config({"mo2_instance_path":str(instance),"profile":"Default","skyrim_game_path":str(game)},config)
            with patch.object(cli,"CONFIG_PATH",config), patch.object(cli,"_extract_root_archive",return_value=content):
                code=cli.main(["root","inspect",str(archive),"--json"])
            self.assertEqual(code,3)

    def test_restore_absent_entry_removes_created_directory(self):
        with tempfile.TemporaryDirectory() as td:
            base=Path(td); instance=self.make_instance(base); config=base/"config.toml"
            cli.save_config({"mo2_instance_path":str(instance),"profile":"Default"},config)
            created=instance/"mods"/"Created Mod"; created.mkdir(); (created/"x.txt").write_text("x",encoding="utf-8")
            tx=instance/"_agent_toolkit_backups"/"test-transaction"; tx.mkdir(parents=True)
            manifest={"schema_version":1,"id":tx.name,"operation":"install","status":"complete","files":[{"kind":"absent","destination":str(created)}]}
            (tx/"manifest.json").write_text(json.dumps(manifest),encoding="utf-8")
            with patch.object(cli,"CONFIG_PATH",config): code=cli.main(["backup","restore",tx.name,"--yes","--json"])
            self.assertEqual(code,0); self.assertFalse(created.exists())


    def test_install_plan_requires_paired_nexus_ids(self):
        out=io.StringIO()
        with contextlib.redirect_stdout(out):
            code=cli.main(["install","plan","Example.zip","--modid","123","--json"])
        self.assertEqual(code,2)
        self.assertIn("provided together",json.loads(out.getvalue())["errors"][0])

    def test_install_plan_freezes_nexus_metadata(self):
        metadata={"provider":"nexus","mod_id":123,"file_id":456,"file_name":"Official.zip",
                  "official_filename":"Official.zip","version":"1.2.3"}
        planned={"id":"plan-1","status":"planned","source_metadata":metadata}
        with patch.object(cli,"load_config",return_value={}), patch.object(cli,"find_7zip",return_value=None), \
             patch.object(cli,"_nexus_file_metadata",return_value=metadata), \
             patch("mo2_agent_toolkit.workflow.create_plan",return_value=planned) as create:
            out=io.StringIO()
            with contextlib.redirect_stdout(out):
                code=cli.main(["install","plan","Example.zip","--modid","123","--file-id","456","--json"])
        self.assertEqual(code,0); self.assertEqual(json.loads(out.getvalue())["data"]["source_metadata"],metadata)
        self.assertEqual(create.call_args.args[-1],metadata)

    def test_legacy_mutating_install_and_update_are_blocked(self):
        with patch.object(cli,"load_config",return_value={}), patch("mo2_agent_toolkit.workflow.fomod_options",return_value=None):
            install=io.StringIO()
            with contextlib.redirect_stdout(install):code_install=cli.main(["install","legacy","Missing.zip","--json"])
            update=io.StringIO()
            with contextlib.redirect_stdout(update):code_update=cli.main(["update","Missing.zip","--json"])
        self.assertEqual(code_install,3); self.assertEqual(code_update,3)
        self.assertIn("install inspect",json.loads(install.getvalue())["errors"][0])
        self.assertIn("install inspect",json.loads(update.getvalue())["errors"][0])



    def test_stdio_is_forced_to_utf8_when_reconfigurable(self):
        class Stream:
            def __init__(self):self.options=None
            def reconfigure(self,**options):self.options=options
        stdout=Stream(); stderr=Stream()
        with patch.object(cli.sys,"stdout",stdout), patch.object(cli.sys,"stderr",stderr):cli._configure_stdio()
        self.assertEqual(stdout.options,{"encoding":"utf-8","errors":"replace"})
        self.assertEqual(stderr.options,{"encoding":"utf-8","errors":"replace"})


if __name__ == "__main__": unittest.main()
