#!/usr/bin/env python3
"""Safely enable/order MO2 mods and plugins with timestamped profile backups."""
import argparse, os, shutil, subprocess, sys
from datetime import datetime
from pathlib import Path

from mo2_agent_toolkit.workflow import WorkflowError, _place_mods

if sys.platform == 'win32': sys.stdout.reconfigure(encoding='utf-8', errors='replace')
SKILL_DIR=Path(__file__).resolve().parent.parent

def env_value(key):
    if os.environ.get(key): return os.environ[key]
    env=SKILL_DIR/'.env'
    if env.exists():
        for raw in env.read_text(encoding='utf-8-sig').splitlines():
            if raw.strip() and not raw.lstrip().startswith('#') and '=' in raw:
                k,v=raw.split('=',1)
                if k.strip()==key: return v.strip().strip('"')
    raise SystemExit(f'ERROR: {key} is not configured')

def read(path): return path.read_text(encoding='utf-8-sig').splitlines()
def write(path, lines): path.write_text('\n'.join(lines)+'\n', encoding='utf-8-sig')
def running_mo2():
    if sys.platform != "win32": return []
    cp=subprocess.run(["tasklist","/FO","CSV","/NH"], capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=10)
    return [line for line in cp.stdout.splitlines() if "modorganizer.exe" in line.casefold()]

def backup(paths):
    transaction=os.environ.get('MO2_TRANSACTION_DIR')
    if transaction: return Path(transaction).name
    stamp=datetime.now().strftime('%Y%m%d-%H%M%S')
    backup_root=Path(env_value('MO2_INSTANCE_PATH'))/'_agent_toolkit_backups'/stamp/'profile'
    backup_root.mkdir(parents=True,exist_ok=True)
    for p in paths: shutil.copy2(p, backup_root/p.name)
    return stamp

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('profile')
    ap.add_argument('--enable-mod', action='append', default=[])
    ap.add_argument('--enable-plugin', action='append', default=[])
    ap.add_argument('--disable-mod', action='append', default=[])
    ap.add_argument('--disable-plugin', action='append', default=[])
    ap.add_argument('--after-plugin', help='Insert ESP/ESL plugins after this plugin; defaults to end')
    placement=ap.add_mutually_exclusive_group()
    placement.add_argument('--before-mod')
    placement.add_argument('--after-mod')
    placement.add_argument('--modlist-top', action='store_true')
    placement.add_argument('--modlist-bottom', action='store_true')
    ap.add_argument('--dry-run', action='store_true')
    a=ap.parse_args()
    root=Path(env_value('MO2_INSTANCE_PATH')); prof=root/'profiles'/a.profile; mods=root/'mods'
    if os.environ.get("MO2_PROFILE_UPDATE_ALLOW_RUNNING") != "1" and running_mo2():
        raise SystemExit("ERROR: ModOrganizer.exe is running; close MO2 before updating profile files")
    files=[prof/n for n in ('modlist.txt','plugins.txt','loadorder.txt')]
    for f in files:
        if not f.is_file(): raise SystemExit(f'ERROR: Missing {f}')
    missing=[m for m in a.enable_mod+a.disable_mod if not (mods/m).is_dir()]
    if missing: raise SystemExit('ERROR: Mod folders missing: '+', '.join(missing))
    ml,pl,lo=map(read,files)
    old_ml,old_pl,old_lo=list(ml),list(pl),list(lo)
    header='# This file was automatically generated by Mod Organizer.'
    for m in a.enable_mod+a.disable_mod: ml=[x for x in ml if x.lstrip('+-') != m]
    if a.enable_mod:
        chosen={'before_mod':a.before_mod,'after_mod':a.after_mod,'modlist_top':a.modlist_top,'modlist_bottom':a.modlist_bottom}
        try: ml,_placement_result=_place_mods(ml,a.enable_mod,chosen)
        except WorkflowError as exc: raise SystemExit(f'ERROR: {exc}') from exc
    else:
        ml=[header]+[x for x in ml if x!=header]
    # Explicitly changed disabled mods remain together without changing untouched mod order.
    if a.disable_mod: ml[1:1]=['-'+m for m in a.disable_mod]
    for n in a.enable_plugin+a.disable_plugin:
        pl=[x for x in pl if x.lstrip('*') != n]
    # Reposition enabled plugins when requested, but preserve disabled plugin order.
    for n in a.enable_plugin:
        lo=[x for x in lo if x != n]
    for n in a.disable_plugin:
        seen=False; kept=[]
        for x in lo:
            if x == n:
                if seen: continue
                seen=True
            kept.append(x)
        lo=kept
    # In MO2, plugins.txt controls activation. Disabled plugins have no asterisk;
    # loadorder.txt may still retain their ordering entry.
    pl.extend(a.disable_plugin)
    esms=[n for n in a.enable_plugin if n.lower().endswith('.esm')]
    others=[n for n in a.enable_plugin if n not in esms]
    esm_i=max((i for i,x in enumerate(pl) if x.lstrip('*').lower().endswith('.esm')),default=-1)+1
    pl[esm_i:esm_i]=['*'+n for n in esms]
    lo_i=max((i for i,x in enumerate(lo) if x.lower().endswith('.esm')),default=-1)+1
    lo[lo_i:lo_i]=esms
    if a.after_plugin:
        pi=next((i+1 for i,x in enumerate(pl) if x.lstrip('*')==a.after_plugin),len(pl))
        li=next((i+1 for i,x in enumerate(lo) if x==a.after_plugin),len(lo))
    else: pi,li=len(pl),len(lo)
    pl[pi:pi]=['*'+n for n in others]; lo[li:li]=others
    changes=(sum(("+"+n) not in old_ml for n in a.enable_mod),
             sum(("-"+n) not in old_ml for n in a.disable_mod),
             sum(("*"+n) not in old_pl or n not in old_lo for n in a.enable_plugin),
             sum(("*"+n) in old_pl or n not in old_pl for n in a.disable_plugin))
    if a.dry_run:
        print(f"Actual changes: enable {changes[0]} mods/{changes[2]} plugins; disable {changes[1]} mods/{changes[3]} plugins; no files changed")
        return
    if ml == old_ml and pl == old_pl and lo == old_lo:
        print(f"No changes needed for profile {a.profile}; requested state already matches disk")
        return
    stamp=backup(files); write(files[0],ml); write(files[1],pl); write(files[2],lo)
    check_ml,check_pl,check_lo=map(read,files)
    failures=[]
    failures += [f"mod not enabled: {n}" for n in a.enable_mod if "+"+n not in check_ml]
    failures += [f"mod not disabled: {n}" for n in a.disable_mod if "-"+n not in check_ml]
    failures += [f"plugin not enabled: {n}" for n in a.enable_plugin if "*"+n not in check_pl or n not in check_lo]
    failures += [f"plugin not disabled: {n}" for n in a.disable_plugin if "*"+n in check_pl or n not in check_pl]
    if failures: raise SystemExit("ERROR: Post-write verification failed: "+"; ".join(failures))
    print(f"Updated and verified profile {a.profile}; backup={stamp}; actual_changes={changes}")
if __name__=='__main__': main()
