#!/usr/bin/env python3
"""
mo2-profile-audit.py — Preflight and post-install audit of a Mod Organizer 2 profile.

Usage:
  python mo2-profile-audit.py <profile> [--pattern <regex>]
  python mo2-profile-audit.py <profile> --json

Environment:
  Reads MO2_INSTANCE_PATH from <skill_dir>/.env.
"""

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(SCRIPT_DIR)
ENV_FILE = os.path.join(SKILL_DIR, ".env")


def load_env():
    env = dict(os.environ)
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE, encoding="utf-8-sig") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    env.setdefault(k, v)
    for key in ['MO2_INSTANCE_PATH']:
        if not env.get(key):
            die(f"{key} is not configured; run mo2-tool setup/auth first")
    return env

def die(msg):
    print(f"ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


ENV = load_env()
INSTANCE = os.environ.get("MO2_INSTANCE_PATH", ENV["MO2_INSTANCE_PATH"])


def read_file(path):
    """Read a text file, return list of lines (stripped)."""
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8-sig") as f:
        return [line.rstrip("\n") for line in f]


def list_processes(patterns):
    """Check if any matching processes are running."""
    result = subprocess.run(
        ["tasklist", "/fo", "csv", "/nh"],
        capture_output=True, text=True, timeout=10
    )
    found = {}
    for pat in patterns:
        for line in result.stdout.split("\n"):
            if pat.lower() in line.lower():
                parts = line.replace('"', "").split(",")
                if len(parts) >= 2:
                    found[parts[0].strip()] = parts[1].strip() if len(parts) > 1 else "?"
    return found


def audit(profile, pattern=None):
    """Run full audit, return dict and (optionally) print results."""
    result = {
        "instance": INSTANCE,
        "profile": profile,
        "timestamp": datetime.now().isoformat(),
        "issues": [],
    }

    # Paths
    mods_dir = os.path.join(INSTANCE, "mods")
    profiles_dir = os.path.join(INSTANCE, "profiles")
    profile_dir = os.path.join(profiles_dir, profile)
    modlist_path = os.path.join(profile_dir, "modlist.txt")
    plugins_path = os.path.join(profile_dir, "plugins.txt")
    loadorder_path = os.path.join(profile_dir, "loadorder.txt")

    # Check essential paths
    for label, p in [("mods", mods_dir), ("profiles", profiles_dir),
                     ("profile", profile_dir), ("modlist.txt", modlist_path)]:
        if not os.path.exists(p):
            result["issues"].append({"severity": "error", "what": f"Missing {label}", "path": p})

    if any(i["severity"] == "error" for i in result["issues"]):
        return result

    # Running processes
    proc_patterns = ["ModOrganizer", "SkyrimSE", "skse64_loader", "LOOT",
                     "Pandora", "Nemesis", "BodySlide"]
    procs = list_processes(proc_patterns)
    result["processes"] = procs
    if procs:
        result["issues"].append({"severity": "warn", "what": "MO2 or game processes are running",
                                 "detail": ", ".join(f"{k}({v})" for k, v in procs.items())})

    # Profiles
    profile_names = [d for d in os.listdir(profiles_dir)
                     if os.path.isdir(os.path.join(profiles_dir, d))]
    result["available_profiles"] = profile_names

    # Mods
    mod_folders = set(d for d in os.listdir(mods_dir)
                       if os.path.isdir(os.path.join(mods_dir, d)))

    # modlist.txt
    raw = read_file(modlist_path) or []
    header = "# This file was automatically generated by Mod Organizer."
    header_positions = [i + 1 for i, line in enumerate(raw) if line == header]
    if header_positions != [1]:
        result["issues"].append({"severity": "error", "what": "modlist.txt header must appear exactly once at line 1", "detail": header_positions})

    managed = [(line[0], line[1:]) for line in raw if line and line[0] in "+-"]
    enabled = [name for op, name in managed if op == "+"]
    disabled = [name for op, name in managed if op == "-"]
    all_listed = set(enabled + disabled)

    missing_folders = [m for m in all_listed if m not in mod_folders]
    unlisted_folders = [m for m in mod_folders if m not in all_listed]

    # Unmanaged tail
    tail = [line for line in raw if line and line.startswith("*")]
    has_dlc_tail = any("Creation Club:" in line or "DLC:" in line for line in tail[-5:] if tail)

    result["modlist"] = {
        "total_managed": len(managed),
        "enabled": len(enabled),
        "disabled": len(disabled),
        "missing_folders": missing_folders,
        "unlisted_folders": unlisted_folders,
        "has_dlc_tail": has_dlc_tail,
    }

    if missing_folders:
        result["issues"].append({"severity": "error",
                                 "what": f"{len(missing_folders)} modlist.txt entries point to missing folders",
                                 "detail": missing_folders[:40]})

    if unlisted_folders:
        result["issues"].append({"severity": "warn",
                                 "what": f"{len(unlisted_folders)} mod folders not listed in modlist.txt",
                                 "detail": unlisted_folders[:40]})

    if not has_dlc_tail:
        result["issues"].append({"severity": "warn",
                                 "what": "modlist.txt tail missing DLC/Creation Club entries"})

    # plugins.txt
    plugins_raw = read_file(plugins_path) or []
    plugins = [p for p in plugins_raw if p and not p.startswith("#")]
    plugin_enabled = [p[1:] for p in plugins if p.startswith("*")]
    plugin_disabled = [p for p in plugins if not p.startswith("*")]
    normalized = [p.lstrip("*").casefold() for p in plugins]
    duplicates = sorted({p for p in normalized if normalized.count(p) > 1})
    if duplicates:
        result["issues"].append({"severity": "error", "what": f"{len(duplicates)} duplicate plugin entries", "detail": duplicates[:40]})
    result["plugins"] = {
        "total": len(plugins),
        "enabled": len(plugin_enabled),
        "disabled": len(plugin_disabled),
    }

    # Pattern search
    if pattern:
        matches = {"modlist": [], "plugins": [], "loadorder": []}
        for i, line in enumerate(raw, 1):
            if re.search(pattern, line, re.I):
                matches["modlist"].append({"line": i, "text": line})
        for i, line in enumerate(plugins or [], 1):
            if re.search(pattern, line, re.I):
                matches["plugins"].append({"line": i, "text": line, "enabled": line.startswith("*")})
        loadorder = read_file(loadorder_path) or []
        for i, line in enumerate(loadorder, 1):
            if re.search(pattern, line, re.I):
                matches["loadorder"].append({"line": i, "text": line})
        result["pattern_matches"] = matches

    return result


def print_audit(result, pattern=None):
    def sec(title):
        print(f"\n== {title} ==")

    sec("Instance")
    print(f"Instance:  {result['instance']}")
    print(f"Profile:   {result['profile']}")

    sec("Running Processes")
    if result["processes"]:
        for name, pid in result["processes"].items():
            print(f"  {name} (PID={pid})")
    else:
        print("  None")

    sec("Profiles")
    for p in result["available_profiles"]:
        mark = " ← active" if p == result["profile"] else ""
        print(f"  {p}{mark}")

    ml = result["modlist"]
    sec("Modlist Summary")
    print(f"Managed:  {ml['total_managed']}")
    print(f"Enabled:  {ml['enabled']}")
    print(f"Disabled: {ml['disabled']}")
    print(f"Missing:  {len(ml['missing_folders'])}")
    print(f"Unlisted: {len(ml['unlisted_folders'])}")

    if ml["missing_folders"]:
        print(f"\n  MISSING FOLDERS ({len(ml['missing_folders'])}):")
        for m in ml["missing_folders"][:40]:
            print(f"    - {m}")
        if len(ml["missing_folders"]) > 40:
            print(f"    ... and {len(ml['missing_folders']) - 40} more")

    if ml["unlisted_folders"]:
        print(f"\n  UNLISTED FOLDERS ({len(ml['unlisted_folders'])}):")
        for m in ml["unlisted_folders"][:40]:
            print(f"    - {m}")
        if len(ml["unlisted_folders"]) > 40:
            print(f"    ... and {len(ml['unlisted_folders']) - 40} more")

    sec("Unmanaged Tail")
    if ml["has_dlc_tail"]:
        print("  DLC/Creation Club entries present ✓")
    else:
        print("  WARNING: DLC/Creation Club entries missing or misplaced!")

    sec("Plugins")
    pl = result["plugins"]
    print(f"Total:   {pl['total']}")
    print(f"Enabled: {pl['enabled']}")
    print(f"Disabled:{pl['disabled']}")

    if pattern and "pattern_matches" in result:
        sec(f"Pattern: {pattern}")
        for section in ["modlist", "plugins", "loadorder"]:
            m = result["pattern_matches"].get(section, [])
            if m:
                print(f"\n  {section}:")
                for entry in m:
                    status = ""
                    if section == "plugins": status = "[ENABLED] " if entry.get("enabled") else "[disabled] "
                    print(f"    L{entry['line']}: {status}{entry['text']}")

    sec("Issues")
    errors = [i for i in result["issues"] if i["severity"] == "error"]
    warns = [i for i in result["issues"] if i["severity"] == "warn"]
    if not errors and not warns:
        print("  No issues found ✓")
    else:
        for e in errors:
            print(f"  ERROR: {e['what']}")
        for w in warns:
            print(f"  WARN:  {w['what']}")


def main():
    parser = argparse.ArgumentParser(description="Audit a Mod Organizer 2 profile")
    parser.add_argument("profile", nargs="?", default="lux",
                        help="Profile name (default: lux)")
    parser.add_argument("--pattern", "-p", help="Regex pattern to search in profile files")
    parser.add_argument("--json", action="store_true", help="Machine-readable output")
    args = parser.parse_args()

    result = audit(args.profile, args.pattern)

    if args.json:
        print(json.dumps(result, indent=2, ensure_ascii=False))
    else:
        print_audit(result, args.pattern)

    # Exit non-zero if errors
    if any(i["severity"] == "error" for i in result["issues"]):
        sys.exit(1)


if __name__ == "__main__":
    main()
